import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLink from "./components/nav-link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="has-background-dark p-5 has-text-white-ter">
          <div className="navbar-menu">
            <div className="navbar-start">
              <NavLink href="/users" className="navbar-item">
                Users
              </NavLink>
              <NavLink href="/add-user" className="navbar-item">
                Add users
              </NavLink>
            </div>
          </div>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
