import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLink from "./lib/components/navlink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navbar has-background-dark py-2 px-2">
          <NavLink
            className="navbar-item has-text-success mx-2"
            href="/"
          >
            Lectures
          </NavLink>
          <NavLink
            className="navbar-item has-text-success"
            href="/lectures/add"
          >
            Add Lecture
          </NavLink>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
